from DesignBase import Design, MultiDesign
from TestDesign import TestDesign
from ThreeSidedPointyThing import ThreeSidedPointyThing
from ThreeArmThinSpiral import ThreeArmThinSpiral
from HoleySpiralArm import HoleySpiralArm
from Nautilus import Nautilus
from Nautilus2 import Nautilus2
from Nautilus3 import Nautilus3
from AlienSpineCircuitTraces import AlienSpineCircuitTraces
from SpiraleyHolePanel import SpiraleyHolePanel